CFLAGS=-std=c11
main: main.c functions.c menu.c functions.h menu.h farben.h
	$(CC)	$(CFLAGS) -o main main.c menu.c functions.c
menu: menu.c farben.h
	$(CC)	$(CFLAGS) -o menu menu.c
farbentest: farbentest.c farben.h
	$(CC)	$(CFLAGS) -o farbentest farbentest.c






